.TH NROFF 1
.SH NAME
nroff \- format text
.SH SYNOPSIS
roff name ...
.SH DESCRIPTION
This program interprets just enough of
.B
nroff -man
to display most common man pages.
.SH SEE ALSO
man(1)
.SH BUGS
TH does not justify.
.br
All arguments are ignored.
.br
Tabs are not accounted for.
.br
Formatting is very rough and wrapping keeps the spaces that
caused the wrap.
.br
Very little of the nroff format is actually implemented.
